problem: cvrp
n_node: 500
k_sparse: 32
alg: faco

n_ants: 100
H: 10
mini_H: 100
rho: 0.5
min_new_edges: 12
alpha: 1.0
beta: 1.0
gamma: 1.0
min_gamma: 0.0

multi_head: true
num_heads: 4
head_zdim: 16

checkpoint: pretrained/cvrp/n500/cvrp_n500_k32_ants100_H2_miniH20_rho0.5_mne12_ppo_lr5e-06_mh4_hg2_hdants_best.pt
dataset: data/CVRP/data/test_set/STAR_CVRPlib_ge1000.txt
run_model_anneal: true
no_baseline: true
summary_json: results/cvrp_star_cvrlib_ge1000_n500_multihead_summary.json

device: cuda:0
seed: 1234
