problem: tsp
n_node: 1000
k_sparse: 32
algo: ppo
alg: faco

n_ants: 100
H: 10
mini_H: 100
epochs: 10
steps_per_epoch: 32
ppo_epochs: 4
ppo_clip: 0.1
ppo_lr: 5.0e-6
lr: null

rho: 0.1
min_new_edges: 12
alpha: 1.0
beta: 1.0
gamma: 1.0
min_gamma: 0.0
train_anneal: false
warmup: true
train_warmup: false
warmup_ratio: 0.5

multi_head: true
num_heads: 4
head_zdim: 16
head_gamma: 0.0
head_score_mode: mean
head_topq: 1
head_diversity_coef: 0.01
head_deploy: ants
head_ant_weights: "25,25,25,25"
head_index: 0
init_single_head_checkpoint: pretrained/tsp/n1000/tsp_n1000_k32_ants100_H10_miniH100_rho0.1_mne12_ppo_lr5e-06_best.pt
head_anchor_checkpoint: pretrained/tsp/n1000/tsp_n1000_k32_ants100_H10_miniH100_rho0.1_mne12_ppo_lr5e-06_best.pt
head_anchor_coef: 1.0
run_tag: balanced_anchor

val_dataset: data/TSP/data/test_set/STAR_TSP_lt1000.txt
val_size: 69
baseline: none
baseline_runs: 1
baseline_time_limit: 0.5

device: cuda:0
seed: 1234
no_wandb: true
save_dir: pretrained
