# n20 static bpp
problem: bpp
n_node: 20
static_prior: true
no_dynamic_feats: false
save_dir: checkpoints_extended/n20
experiment_name: bpp_n20_static
capacity: 150.0
k_sparse: 20
n_ants: 20
H: 5
mini_H: 5
epochs: 15
steps_per_epoch: 20
val_size: 8
aco_iters_per_sample: 20
rho: 0.9
alpha: 1.0
beta: 1.0
lr: 0.0003
gamma: 1.0
min_gamma: 0.0
warmup: 0
train_anneal: false
no_logit_net: false
grad_checkpointing: false
multi_head: false
device: cuda:0
seed: 1234
save_interval: 1
use_wandb: false
