problem: cvrp
n_node: 500
k_sparse: 32
algo: ppo
alg: faco

n_ants: 100
H: 2
mini_H: 20
epochs: 10
steps_per_epoch: 8
ppo_epochs: 4
ppo_clip: 0.1
ppo_lr: 5.0e-6
lr: null

rho: 0.5
min_new_edges: 12
alpha: 1.0
beta: 1.0
gamma: 1.0
min_gamma: 0.0
train_anneal: false
warmup: true
train_warmup: false
warmup_ratio: 0.5

seed: 1234
grad_checkpointing: false
ablation_pheromone_features: false
ablation_incumbent_features: false
no_logit_net: false
no_dynamic_feats: false
edge_feature_set: compact3

multi_head: true
num_heads: 4
head_zdim: 16

val_dataset: data/CVRP/data/validation_set/validation_cvrp1000_n128_C250.txt
val_size: 16
baseline: none
baseline_runs: 1
baseline_time_limit: 0.5

device: cuda:0
seed: 1234
no_wandb: true
save_dir: pretrained
